
import json
import re

file_path = '/home/alzubair/my_projects/qrcode_menus/lang/ar.json'

with open(file_path, 'r') as f:
    data = json.load(f)

translations = {
    # General & Apps
    "Apps": "التطبيقات",
    "Apps settings": "إعدادات التطبيقات",
    "Sort order updated": "تم تحديث ترتيب الفرز",
    "Make": "صنع",
    "default": "افتراضي",
    "Localisation": "الترجمة",
    "Money conversion": "تحويل الأموال",
    "Currency": "العملة",
    "Actions": "الإجراءات",
    "Download": "تحميل",
    "Print": "طباعة",
    "Export": "تصدير",
    "Import": "استيراد",
    "Settings": "الإعدادات",
    "Close": "إغلاق",
    "Save": "حفظ",
    "Update": "تحديث",
    "Delete": "حذف",
    "Edit": "تعديل",
    "Create": "إنشاء",
    "View": "عرض",
    "Add": "إضافة",
    "New": "جديد",
    
    # Drivers
    "Driver": "السائق",
    "Drivers": "السائقين",
    "Driver name": "اسم السائق",
    "Driver email": "بريد السائق",
    "Driver phone": "هاتف السائق",
    "Driver not found!": "السائق غير موجود!",
    "User is not a driver!": "المستخدم ليس سائقاً!",
    "Driver now off line": "السائق الآن غير متصل",
    "Driver now online": "السائق الآن متصل",
    "Driver accepts order": "السائق قبل الطلب",
    "Driver reject order": "السائق رفض الطلب",
    "Order not on this driver": "الطلب ليس مع هذا السائق",
    "Driver account created. Please wait for a call from us to activate your account.": "تم إنشاء حساب السائق. يرجى انتظار اتصال منا لتفعيل حسابك.",
    "Driver successfully created.": "تم إنشاء السائق بنجاح.",
    "Driver successfully deleted.": "تم حذف السائق بنجاح.",
    "Driver successfully activated.": "تم تفعيل السائق بنجاح.",
    "Assign to driver": "تعيين للسائق",
    "Assigned to driver": "تم التعيين للسائق",

    # Orders
    "Order": "الطلب",
    "Orders": "الطلبات",
    "Order created.": "تم إنشاء الطلب.",
    "Order updated.": "تم تحديث الطلب.",
    "Order status succesfully changed.": "تم تغيير حالة الطلب بنجاح.",
    "Order succesfully rated!": "تم تقييم الطلب بنجاح!",
    "Order not on this vendor": "الطلب ليس لهذا البائع",
    "There is new order": "يوجد طلب جديد",
    "You have just received an order": "لقد تلقيت للتو طلباً",
    "Send order on WhatsApp": "إرسال الطلب عبر واتساب",
    "Verify": "تحقق",
    "Your verification code is": "رمز التحقق الخاص بك هو",
    "Pay now": "ادفع الآن",
    "The payment attempt failed": "محاولة الدفع فشلت",
    
    # Success/Error Messages
    "New language successfully created.": "تم إنشاء لغة جديدة بنجاح.",
    "Address successfully added.": "تم إضافة العنوان بنجاح.",
    "Address successfully deactivated.": "تم تعطيل العنوان بنجاح.",
    "User successfully created.": "تم إنشاء المستخدم بنجاح.",
    "User successfully updated.": "تم تحديث المستخدم بنجاح.",
    "User successfully deleted.": "تم حذف المستخدم بنجاح.",
    "Item successfully updated.": "تم تحديث العنصر بنجاح.",
    "Item successfully deleted.": "تم حذف العنصر بنجاح.",
    "Items successfully imported": "تم استيراد العناصر بنجاح",
    "Extras successfully added/modified.": "تم إضافة/تعديل الإضافات بنجاح.",
    "Extras successfully updated.": "تم تحديث الإضافات بنجاح.",
    "Extras successfully deleted.": "تم حذف الإضافات بنجاح.",
    "City was added": "تم إضافة المدينة",
    "City was updated": "تم تحديث المدينة",
    "Item was deleted.": "تم حذف العنصر.",
    "Coupon code applied successfully.": "تم تطبيق كود الكوبون بنجاح.",
    "Plan successfully created!": "تم إنشاء الخطة بنجاح!",
    "Plan successfully updated!": "تم تحديث الخطة بنجاح!",
    "Plan successfully deleted!": "تم حذف الخطة بنجاح!",
    "Plan successfully updated.": "تم تحديث الخطة بنجاح.",
    "Profile successfully updated.": "تم تحديث الملف الشخصي بنجاح.",
    "Password successfully updated.": "تم تحديث كلمة المرور بنجاح.",
    "Category successfully created.": "تم إنشاء الفئة بنجاح.",
    "Category name successfully updated.": "تم تحديث اسم الفئة بنجاح.",
    "Category successfully deleted.": "تم حذف الفئة بنجاح.",
    "Restaurant successfully created.": "تم إنشاء المطعم بنجاح.",
    "Restaurant successfully updated.": "تم تحديث المطعم بنجاح.",
    "Restaurant successfully deactivated.": "تم تعطيل المطعم بنجاح.",
    "Restaurant successfully removed from database.": "تم إزالة المطعم من قاعدة البيانات بنجاح.",
    "Restaurant successfully imported.": "تم استيراد المطعم بنجاح.",
    "Restaurant successfully activated.": "تم تفعيل المطعم بنجاح.",
    "Page successfully created!": "تم إنشاء الصفحة بنجاح!",
    "Page successfully updated!": "تم تحديث الصفحة بنجاح!",
    "Page successfully deleted!": "تم حذف الصفحة بنجاح!",
    "Settings successfully updated!": "تم تحديث الإعدادات بنجاح!",
    "Working hours successfully updated!": "تم تحديث ساعات العمل بنجاح!",
    "Client successfully deleted.": "تم حذف العميل بنجاح.",
    
    # Cities & Locations
    "Cities": "المدن",
    "City": "المدينة",
    "Select city": "اختر المدينة",
    "Edit city": "تعديل المدينة",
    "New": "جديد",
    "City image ( 200x200 )": "صورة المدينة ( 200x200 )",
    "Find us in these cities and many more!": "تجدنا في هذه المدن وغيرها الكثير!",
    "Restaurants in": "متاعم في",
    
    # Plans & Subscriptions
    "Plan": "الخطة",
    "Plans": "الخطط",
    "Subscribe": "اشتراك",
    "Subscription": "الاشتراك",
    "Cancel Subscription": "إلغاء الاشتراك",
    "Change Subscription Plan": "تغيير خطة الاشتراك",
    "Plan update!": "تحديث الخطة!",
    "Please subscribe to a plan first": "يرجى الاشتراك في خطة أولاً",
    "The coupon promotion code has been expired or the limit is exceeded.": "كود الكوبون منتهي الصلاحية أو تم تجاوز الحد.",
    "Feature image": "صورة مميزة",
    "Limit": "الحد",
    "Unlimited": "غير محدود",
    
    # QR & Menus (Specific to project)
    "Restaurant QR Generators": "منشئي QR للمطعم",
    "SELECT QR STYLE": "اختر نمط QR",
    "SELECT QR COLOR": "اختر لون QR",
    "Color 1": "لون 1",
    "Color 2": "لون 2",
    "QR Downloader": "تحميل QR",
    "Download JPG": "تحميل JPG",
    "Menu Print template": "قالب طباعة القائمة",
    "Download Print Templates": "تحميل قوالب الطباعة",
    
    # Admin & Settings
    "Admin": "مسؤول",
    "Owner": "المالك",
    "Manage": "إدارة",
    "Management": "الإدارة",
    "Overview": "نظرة عامة",
    "Sales value": "قيمة المبيعات",
    "Total orders": "إجمالي الطلبات",
    "Performance": "الأداء",
    "No sales right now!": "لا توجد مبيعات الآن!",
    "No orders right now!": "لا توجد طلبات الآن!",
    "Setup": "الإعداد",
    "System": "النظام",
    "Site Name": "اسم الموقع",
    "Site Description": "وصف الموقع",
    "Sitemap": "خريطة الموقع",
    "Regenerate sitemap": "إعادة إنشاء خريطة الموقع",
    "Sitemap Regenerated": "تم إعادة إنشاء خريطة الموقع",
    "No Access": "لا يوجد وصول",
    "No Access.": "لا يوجد وصول.",
    "Forbidden": "ممنوع",
    "Not Found": "غير موجود",
    "Server Error": "خطأ في الخادم",
    "Error 404 - Not found!": "خطأ 404 - غير موجود!",
    "Error 500 on system!": "خطأ 500 في النظام!",
    "Some currencies need this field to be unselected. By default it should be selected": "بعض العملات تحتاج لإلغاء تحديد هذا الحقل. افتراضياً يكون محدداً",
    
    # Forms
    "Name": "الاسم",
    "Email": "البريد الإلكتروني",
    "Phone": "الهاتف",
    "Password": "كلمة المرور",
    "Confirm Password": "تأكيد كلمة المرور",
    "Address": "العنوان",
    "Comment": "التعليق",
    "Message": "الرسالة",
    "Submit": "إرسال",
    "Select": "تحديد",
    "Options": "الخيارات",
    "Variants": "المتغيرات",
    "No options values selected": "لم يتم تحديد قيم للخيارات",
    
    # Time
    "Jan": "يناير", "Feb": "فبراير", "Mar": "مارس", "Apr": "أبريل", "May": "مايو", "Jun": "يونيو",
    "Jul": "يوليو", "Aug": "أغسطس", "Sep": "سبتمبر", "Oct": "أكتوبر", "Nov": "نوفمبر", "Dec": "ديسمبر",
    "January": "يناير", "February": "فبراير", "March": "مارس", "April": "أبريل", "May": "مايو", "June": "يونيو",
    "July": "يوليو", "August": "أغسطس", "September": "سبتمبر", "October": "أكتوبر", "November": "نوفمبر", "December": "ديسمبر",
    "Monday": "الاثنين", "Tuesday": "الثلاثاء", "Wednesday": "الأربعاء", "Thursday": "الخميس", "Friday": "الجمعة", "Saturday": "السبت", "Sunday": "الأحد",
    
    # Common
    "Welcome!": "مرحبا!",
    "Hi": "مرحبا",
    "Hello": "أهلا",
    "Yes": "نعم",
    "No": "لا",
    "Ok": "موافق",
    "Cancel": "إلغاء",
    "Back": "رجوع",
    "Next": "التالي",
    "Previous": "السابق",
    "Click here": "اضغط هنا",
    "Read more": "اقرأ المزيد",
    "Contact Us": "اتصل بنا",
    "About Us": "من نحن",
    "Terms": "الشروط",
    "Privacy": "الخصوصية",
    "Login": "تسجيل الدخول",
    "Logout": "تسجيل الخروج",
    "Register": "تسجيل",
    "My Account": "حسابي",
    "Dashboard": "لوحة التحكم",
    "Latest version": "أحدث إصدار",
    "Social Links": "روابط التواصل الاجتماعي",
    "Mobile App": "تطبيق الجوال",
    "Site Logo": "شعار الموقع",
    "Restaurant Default Image": "صورة المطعم الافتراضية",
    "Restaurant Details Cover Image": "صورة غلاف تفاصيل المطعم",
    "Favicon": "أيقونة الموقع (Favicon)",
    "Search Cover": "غلاف البحث",
    "Site Logo Dark": "شعار الموقع (داكن)",
    "Front QR": "QR الواجهة",
    "Flayer image": "صورة المنشور",
    "Feature image #1": "صورة مميزة #1",
    "Feature image #2": "صورة مميزة #2",
    "Feature image #3": "صورة مميزة #3",
    "Feature image #4": "صورة مميزة #4",
    "Feature image #5": "صورة مميزة #5",
    "Feature image #6": "صورة مميزة #6",
    "Add driver": "إضافة سائق",
    "Acceptance rating": "تقييم القبول",
    "Are you sure you want to delete this user?": "هل أنت متأكد أنك تريد حذف هذا المستخدم؟",
    "Are you sure you want to deactivate this user?": "هل أنت متأكد أنك تريد تعطيل هذا المستخدم؟",
    "Finalize order": "إتمام الطلب",
    "Client information": "معلومات العميل",
    "Settings Management": "إدارة الإعدادات",
    "Remove demo data": "إزالة البيانات التجريبية",
    "Demo Stripe Credentials": "بيانات Stripe التجريبية",
    "Pay via iDeal": "دفع عبر iDeal",
    "Name on card": "الاسم على البطاقة",
    "Submit payment": "إرسال الدفع",
    "Back to list": "العودة للقائمة",
    "Minimum order": "الحد الأدنى للطلب",
    "Hmmm... Nothing found!": "هممم... لم يتم العثور على شيء!",
    "Owner email": "بريد المالك",
    "Birth Date": "تاريخ الميلاد",
    "Address number": "رقم العنوان",
    "Intercom": "الانتركم",
    "Floor": "الطابق",
    "Entry number": "رقم المدخل",
    "You don`t have any address. Please add new one": "ليس لديك أي عنوان. يرجى إضافة واحد جديد",
    "Or add new": "أو أضف جديد",
    "Add new": "أضف جديد",
    "Your phone here": "رقم هاتفك هنا",
    "Your comment here": "تعليقك هنا",
    "Visit": "زيارة",
    "We are happy that email works now.": "نحن سعداء بأن البريد الإلكتروني يعمل الآن.",
    "QR": "QR",
    "Total": "الإجمالي",
    "Active": "نشط",
    "Driver information": "معلومات السائق",
    "Realtime map": "خريطة لحظية",
    "Delivery activities": "نشاطات التوصيل",
    "Plan period": "مدة الخطة",
    "Monthly": "شهري",
    "Anually": "سنوي",
    "Ordering": "الطلب",
    "Update plan": "تحديث الخطة",
    "Add plan": "إضافة خطة",
    "Items limit": "حد العناصر",
    "Paddle ID": "معرف Paddle",
    "Stripe ID": "معرف Stripe",
    "PayPal ID": "معرف PayPal",
    "Mollie ID": "معرف Mollie",
    "Paystack ID": "معرف Paystack",
    "Are you sure you want to delete this plan?": "هل أنت متأكد أنك تريد حذف هذه الخطة؟",
    "You don`t have any plans": "ليس لديك أي خطط",
    "Back to plans": "العودة للخطط",
    "Plan information": "معلومات الخطة",
    "m": "شهر",
    "y": "سنة",
    "Current Plan": "الخطة الحالية",
    "Switch to": "التحويل إلى",
    "Plan price": "سعر الخطة",
    "Subscribe to": "اشتراك في",
    "Your current plan": "خطتك الحالية",
    "You are currently using the": "أنت تستخدم حاليا",
    "plan": "خطة",
    "Update subscription": "تحديث الاشتراك",
    "Cancel subscription": "إلغاء الاشتراك",
    "Date of Birth": "تاريخ الميلاد",
    "Create account": "إنشاء حساب",
    "Back to login": "العودة لتسجيل الدخول",
    "Verify Your Email Address": "تحقق من عنوان بريدك الإلكتروني",
    "A fresh verification link has been sent to your email address.": "تم إرسال رابط تحقق جديد إلى بريدك الإلكتروني.",
    "Before proceeding, please check your email for a verification link.": "قبل المتابعة، يرجى التحقق من بريدك الإلكتروني للحصول على رابط التحقق.",
    "If you did not receive the email": "إذا لم تستلم البريد الإلكتروني",
    "click here to request another": "انقر هنا لطلب واحد آخر",
    "DEMO credentials:": "بيانات الدخول التجريبية:",
    "ADMIN": "مسؤول",
    "Username": "اسم المستخدم",
    "OWNER": "المالك",
    "DRIVER": "السائق",
    "CLIENT": "العميل",
    "order": "طلب",
    "Hello ": "مرحبا ",
    "This is a test email from ": "هذا بريد إلكتروني تجريبي من ",
    "Switch to ": "التحويل إلى ",
    "Plan price ": "سعر الخطة ",
    "Sign in with": "تسجيل الدخول عبر",
    "Remember me": "تذكرني",
    "Create new account": "إنشاء حساب جديد",
    "Verify your profile": "تحقق من ملفك الشخصي",
    "Thanks for registering with our platform. We will sent you message on your phone number. Provide the code below.": "شكراً لتسجيلك في منصتنا. سنرسل لك رسالة على رقم هاتفك. أدخل الرمز أدناه.",
    "Verification Code": "رمز التحقق",
    "Enter your verification code": "أدخل رمز التحقق الخاص بك",
    "Verify profile": "تحقق من الملف الشخصي",
    "Insert": "إدراج",
    "User Profile": "ملف المستخدم",
    "Active from": "نشط من",
    "Active to": "نشط إلى",
    "Banner": "بانر",
    "Edit banner": "تعديل البانر",
    "New banner": "بانر جديد",
    "Banner information": "معلومات البانر",
    "Coupon": "كوبون",
    "Edit coupon": "تعديل الكوبون",
    "New coupon": "كوبون جديد",
    "Coupon information": "معلومات الكوبون",
    "Deleted": "محذوف",
    "Not active": "غير نشط",
    "Login as": "تسجيل الدخول بصفة",
    "Are you sure you want to deactivate this restaurant?": "هل أنت متأكد أنك تريد تعطيل هذا المطعم؟",
    "Register your restaurant": "سجل مطعمك",
    "Information": "معلومات",
    "Restaurant information": "معلومات المطعم",
    "Restaurant Name here": "اسم المطعم هنا",
    "Owner information": "معلومات المالك",
    "Owner Name here": "اسم المالك هنا",
    "Owner Email here": "بريد المالك هنا",
    "Owner Phone here": "هاتف المالك هنا",
    "View it": "عرضه",
    "Go back": "عد للخلف",
    "Share Menu": "شارك القائمة",
    "Share your menu with your audience": "شارك قائمتك مع جمهورك",
    "Download QR Code": "تحميل رمز QR",
    "Subscription plan": "خطة الاشتراك",
    "Clear Delivery Area": "مسح منطقة التوصيل",
    "Select your options": "اختر خياراتك",
    "Extras": "إضافات",
    "Import restaurants from CSV": "استيراد المطاعم من CSV",
    "About": "حول",
    "Review": "مراجعة",
    "There are no reviews yet.": "لا توجد مراجعات بعد.",
    "Enter Minimum order value": "أدخل الحد الأدنى لقيمة الطلب",
    "Fee percent": "نسبة الرسوم",
    "Static fee": "رسوم ثابتة",
    "Static Fee": "رسوم ثابتة",
    "Is Featured": "مميز",
    "Restaurant Image": "صورة المطعم",
    "Restaurant Cover Image": "صورة غلاف المطعم",
    "All categories": "كل الفئات",
    "Call Waiter": "استدعاء النادل",
    "Call Now": "اتصل الآن",
    "User information": "معلومات المستخدم",
    "Are you sure you want to cancel the account and all their data?": "هل أنت متأكد أنك تريد إلغاء الحساب وجميع البيانات؟",
    "Deliveries": "التوصيلات",
    "Search for restaurant, cuisines, and dishes": "ابحث عن مطعم، مطابخ، وأطباق",
    "days": "أيام",
    "Sales Volume": "حجم المبيعات",
    "Number of restaurants": "عدد المطاعم",
    "restaurants": "مطاعم",
    "Number of items": "عدد العناصر",
    "items": "عناصر",
    "Views": "مشاهدات",
    "views": "مشاهدات",
    "Dynamic Fee": "رسوم ديناميكية",
    "Total Fee": "إجمالي الرسوم",
    "Change location": "تغيير الموقع",
    "Enter your street or address": "أدخل شارعك أو عنوانك",
    "Get my current location": "الحصول على موقعي الحالي",
    "or": "أو",
    "Find your meal": "ابحث عن وجبتك",
    "DELIVERING TO": "التوصيل إلى",
    "change": "تغيير",
    "Like us on Facebook": "تابعنا على فيسبوك",
    "Follow us on Instagram": "تابعنا على انستغرام",
    "Pricing plans": "خطط الأسعار",
    "Register visit": "سجل زيارة",
    "Banners": "البنرات",
    "Site Settings": "إعدادات الموقع",
    "Customers log": "سجل العملاء",
    "Coupons": "الكوبونات",
    "Cart is empty": "السلة فارغة",
    "Continue Shopping": "مواصلة التسوق",
    "External plugins": "الإضافات الخارجية",
    "Loyalty Platform": "منصة الولاء",
    "latest": "الأحدث",
    "Short name": "الاسم المختصر",
    "You don`t have any addresses": "ليس لديك أي عناوين",
    "New address here": "عنوان جديد هنا",
    "Add user": "إضافة مستخدم",
    "Dine In / Takeaway": "تناول داخل المطعم / سفري",
    "Dine In": "تناول داخل المطعم",
    "Takeaway": "سفري",
    "Place an order": "وضع طلب",
    "Delivery / Pickup": "توصيل / استلام",
    "Delivery Address": "عنوان التوصيل",
    "-- select an option -- ": "-- اختر خياراً -- ",
    "Today working hours": "ساعات العمل اليوم",
    "Delivery time": "وقت التوصيل",
    "Pickup time": "وقت الاستلام",
    "Order can not be placed since restaurant will be / is closed.": "لا يمكن وضع الطلب لأن المطعم مغلق.",
    "HAVE A PROMO CODE?": "لديك كود خصم؟",
    "Enter your promo code here": "أدخل كود الخصم هنا",
    "Only one promo code may be user per order": "يمكن استخدام كوبون واحد فقط للطلب",
    "Apply": "تطبيق",
    "TOTAL": "الإجمالي",
    "Cash / Card Terminal": "نقد / جهاز دفع",
    "Cash on pickup": "نقد عند الاستلام",
    "Pay with PayPal": "دفع عبر PayPal",
    "Pay with Paystack": "دفع عبر Paystack",
    "Pay with Mollie": "دفع عبر Mollie",
    "Send Whatsapp Order": "أرسل الطلب عبر واتساب",
    "Send Facebook Order": "أرسل الطلب عبر فيسبوك",
    "I agree to the Terms and Conditions and Privacy Policy": "أوافق على الشروط والأحكام وسياسة الخصوصية",
    "Demo cards": "بطاقات تجريبية",
    "You're all set!": "أنت جاهز تماماً!",
    "Go back to restaurant": "عودة للمطعم",
    "Go Back": "العودة",
    "Refresh": "تحديث",
    "Live orders": "طلبات مباشرة",
    "New Orders": "طلبات جديدة",
    "Done": "تم",
    "Status History": "سجل الحالة",
    "Your overall rating": "تقييمك العام",
    "Order time to prepare in minutes": "وقت تحضير الطلب بالدقائق",
    "Status from": "الحالة من",
    "ID": "المعرف",
    "Created": "تم الإنشاء",
    "Time Slot": "الوقت",
    "Method": "الطريقة",
    "Last status": "آخر حالة",
    "Client Information": "معلومات العميل",
    "Contact": "اتصال",
    "Table Information": "معلومات الطاولة",
    "Table:": "طاولة:",
    "Area:": "منطقة:",
    "VAT ": "الضريبة ",
    "Time to prepare": "وقت التحضير",
    "minutes": "دقائق",
    "NET": "الصافي",
    "Sub Total": "المجموع الفرعي",
    "Payment status": "حالة الدفع",
    "Delivery method": "طريقة التوصيل",
    "Time slot": "وقت التوصيل",
    "Dine method": "طريقة تناول الطعام",
    "Dine in": "تناول داخل المطعم",
    "No actions for you right now!": "لا توجد إجراءات لك الآن!",
    "Picked Up": "تم الاستلام",
    "Date From": "التاريخ من",
    "Date from": "التاريخ من",
    "Date to": "التاريخ إلى",
    "Filter by Restaurant": "تصفية حسب المطعم",
    "Select an option": "اختر خياراً",
    "Filter by Client": "تصفية حسب العميل",
    "Filter by Driver": "تصفية حسب السائق",
    "Download report": "تحميل التقرير",
    "You don`t have any orders": "ليس لديك أي طلبات",
    "Table / Method": "طاولة / طريقة",
    "Order Review": "مراجعة الطلب",
    "Poor": "سيء",
    "Fair": "مقبول",
    "Good": "جيد",
    "Excellent": "ممتاز",
    "WOW": "مذهل",
    "Order comment": "تعليق الطلب",
    "Order comment here": "تعليق الطلب هنا",
    "Fee information": "معلومات الرسوم",
    "Your current static fee on each order is:": "رسومك الثابتة الحالية على كل طلب هي:",
    "Your current percentage fee on each order is:": "نسبتك الحالية على كل طلب هي:",
    "on the order value": "على قيمة الطلب",
    "Fees": "الرسوم",
    "Platform fee": "رسوم المنصة",
    "Processor fee": "رسوم المعالج",
    "Platform profit": "ربح المنصة",
    "Net Price + VAT": "السعر الصافي + الضريبة",
    "Net Price": "السعر الصافي",
    "Total Price": "السعر الإجمالي",
    "Stripe connect": "اتصال Stripe",
    "We use Stripe to collect payments. Connect now, and we will send your funds from cart payments dirrectly to your Stripe account": "نستخدم Stripe لجمع المدفوعات. اتصل الآن، وسنسل أموالك من مدفوعات السلة مباشرة إلى حساب Stripe الخاص بك",
    "Connect with Stripe Connect": "اتصل مع Stripe Connect",
    "Stripe account": "حساب Stripe",
    "Stripe details submited": "تم تقديم تفاصيل Stripe",
    "Update Stripe connection": "تحديث اتصال Stripe",
    "Edit Restaurant Menu": "تعديل قائمة المطعم",
    "Select variant or leave empty for all": "اختر المتغير أو اتركه فارغاً للكل",
    "Back to items": "العودة للعناصر",
    "Item information": "معلومات العنصر",
    "VAT percentage( calculated into item price )": "نسبة الضريبة (محسوبة في سعر العنصر)",
    "Item VAT percentage": "نسبة ضريبة العنصر",
    "Are you sure you want to delete this item?": "هل أنت متأكد أنك تريد حذف هذا العنصر؟",
    "For": "لـ",
    "All variants": "كل المتغيرات",
    "Selected": "المحدد",
    "Are you sure you want to delete this extras?": "هل أنت متأكد أنك تريد حذف هذه الإضافات؟",
    "Item available": "العنصر متاح",
    "Add page": "إضافة صفحة",
    "Show as link": "إظهار كرابط",
    "Click for details": "اضغط للتفاصيل",
    "Are you sure you want to delete this page?": "هل أنت متأكد أنك تريد حذف هذه الصفحة؟",
    "You don`t have any pages": "ليس لديك أي صفحات",
    "Page": "الصفحة",
    "Back to pages": "العودة للصفحات",
    "Page information": "معلومات الصفحة",
    "Title here ...": "العنوان هنا ...",
    "Rating": "التقييم",
    "You do not have any address, please add new one.": "ليس لديك أي عنوان، يرجى إضافة واحد جديد.",
    "You don't have any address, please add new one.": "ليس لديك أي عنوان، يرجى إضافة واحد جديد.",
    "New address added successfully!": "تم إضافة عنوان جديد بنجاح!",
    "You can not delete this address!": "لا يمكنك حذف هذا العنوان!",
    "Feature image ( 128x128 )": "صورة مميزة ( 128x128 )",
    "Enter title": "أدخل العنوان",
    "Enter description": "أدخل الوصف",
    "Landing Page": "صفحة الهبوط",
    "New feature": "ميزة جديدة",
    "Edit this feature": "تعديل هذه الميزة",
    "Enter link name": "أدخل اسم الرابط",
    "Enter link URL": "أدخل رابط URL",
    "Processes": "العمليات",
    "New process": "عملية جديدة",
    "Edit this process": "تعديل هذه العملية",
    "Successfully migrated to multi language menus": "تم الترحيل بنجاح لقوائم متعددة اللغات",
    "Successfully updated to version v": "تم التحديث بنجاح للإصدار v",
    "There is nothing to update!": "لا يوجد شيء لتحديثه!",
    "Author image ( 48x48 )": "صورة المؤلف ( 48x48 )",
    "Enter author name": "أدخل اسم المؤلف",
    "Enter short description": "أدخل وصفاً قصيراً",
    "Enter testimonial comment": "أدخل تعليق الشهادة",
    "New testimonial": "شهادة جديدة",
    "Edit this testimonial": "تعديل هذه الشهادة",
    "Hi, I'd like to place an order": "مرحبا، أود تقديم طلب",
    "will confirm your order upon receiving the message.": "سيتم تأكيد طلبك عند استلام الرسالة.",
    "Payment for order on": "الدفع للطلب في",
}

# Apply Translations
count = 0
for key, value in data.items():
    if key in translations:
        # Check if already translated (heuristic: if value contains Arabic chars)
        # But user says "still not completely translate", so we should force update if we have a match
        # To be safe, let's update if current value == key OR matches English
        # Update if value is same as key, or empty, or matches English (simple check)
        if data[key] == key or not data[key] or data[key] == translations[key]:
             data[key] = translations[key]
             count += 1
        else:
             # It has a different value. Let's overwrite anyway if it looks like English (all ASCII)
             # This is a bit aggressive but needed for "massive" translation
             if all(ord(c) < 128 for c in data[key]):
                 data[key] = translations[key]
                 count += 1
    # Check for "successfully created" pattern
    elif "successfully created" in key.lower() and key not in translations:
         # Attempt partial replacement
         pass

print(f"Updated {count} keys from massive script.")

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=4, ensure_ascii=False)
